# Generated by Django 5.1.4 on 2024-12-23 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000000)),
                ('description', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(default='blog.png', upload_to='blogs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
