# Generated by Django 5.1.4 on 2025-02-08 10:01

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000000)),
                ('description', models.TextField(default='')),
                ('content', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(default='blog.png', upload_to='blogs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=100)),
                ('items', models.TextField(default='')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10000000000)),
                ('image', models.ImageField(default='', upload_to='policies/')),
                ('file', models.FileField(upload_to='uploads/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('number', models.IntegerField(unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10000)),
                ('content', markdownx.models.MarkdownxField()),
                ('description', models.TextField(default='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(8, 0))),
                ('venue', models.CharField(default='', max_length=100000000000)),
                ('attendees', models.IntegerField(default=1)),
                ('location', models.CharField(default='', max_length=100000000)),
                ('image', models.ImageField(default='events.png', upload_to='events/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10000)),
                ('policies', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.policies')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('number', models.IntegerField(unique=True)),
                ('constituency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=1000)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999999)])),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.county')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='core.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(99999999999999)])),
                ('skills', models.TextField(blank=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.county')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.ward')),
            ],
            options={
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(default='')),
                ('level', models.CharField(choices=[('national', 'National'), ('county', 'County'), ('ward', 'Ward')], max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.county')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000000)),
                ('position', models.CharField(default='', max_length=1000)),
                ('about', models.TextField(default='')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.county')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.ward')),
            ],
        ),
    ]
