# Generated by Django 5.1.4 on 2024-12-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10000)),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(default='', max_length=100000000000)),
                ('location', models.CharField(default='', max_length=100000000)),
                ('image', models.ImageField(default='events.png', upload_to='events/')),
            ],
        ),
    ]
