# Generated by Django 5.1.4 on 2024-12-25 10:48

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000000)),
                ('position', models.CharField(default='', max_length=1000)),
                ('about', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=10000000000)),
                ('file', models.FileField(upload_to='uploads/documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
