# Generated by Django 5.1.4 on 2025-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='county',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
