# Generated by Django 5.1.4 on 2024-12-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidate_policies_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=20)),
                ('role', models.CharField(default='', max_length=100)),
                ('skills', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.county')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.county')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ward'),
        ),
    ]
