# Generated by Django 5.1.4 on 2025-02-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_volunteer_county_remove_volunteer_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='constituencies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.constituency'),
        ),
    ]
