# Generated by Django 5.1.4 on 2024-12-26 10:44

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', markdownx.models.MarkdownxField()),
                ('level', models.CharField(choices=[('national', 'National'), ('county', 'County'), ('ward', 'Ward')], max_length=20)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.county')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ward')),
            ],
        ),
    ]
