# Generated by Django 5.1.4 on 2025-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_request_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='response_description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
