# Generated by Django 5.1.4 on 2025-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='role',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='skills',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
