# Generated by Django 5.1.4 on 2025-01-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_role_volunteer_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
