# Generated by Django 5.1.4 on 2025-01-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_category_options_event_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('skills', models.TextField(blank=True)),
            ],
        ),
    ]
