# Generated by Django 5.1.4 on 2025-01-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_members_options_alter_members_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.county'),
        ),
        migrations.AlterField(
            model_name='members',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ward'),
        ),
    ]
