# Generated by Django 5.1.4 on 2025-01-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_members_county_alter_members_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
