# Generated by Django 5.1.4 on 2025-01-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_imagecategory_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
