# Generated by Django 5.1.4 on 2025-01-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_issue_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.AddField(
            model_name='policies',
            name='image',
            field=models.ImageField(default='', upload_to='policies/'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='ImageCategory',
        ),
    ]
