# Generated by Django 5.1.4 on 2025-01-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_tag_blog_policies_image_delete_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='policies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.policies'),
        ),
    ]
