# Generated by Django 5.1.4 on 2025-01-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_remove_ward_county_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='constituency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.constituency'),
        ),
    ]
