# Generated by Django 5.1.4 on 2025-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ward_constituency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
