# Generated by Django 5.1.4 on 2025-01-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_order_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
    ]
